### ISSUE TITLE
fail to use

### ISSUE THREAD

**Issue by molecular** [andrewsomething/github-download-stats#2]
Hi,

does this only work for github enterprise?

I'm trying like this:

```
#> github-download-stats -repo chaintipper -owner molecular -release "1.0-beta18"                                                                            
Repository: molecular/chaintipper
```

and there's no output at all (except the "Repository:..." line)

Do I need to give API token or something? EDIT: tried with an api token, also same output

I feel lost.

**Comment by andrewsomething** [comment]
It looks like `molecular/chaintipper` currently only has pre-releases:

https://github.com/molecular/chaintipper/releases

And I've been filtering those out:

https://github.com/andrewsomething/github-download-stats/blob/2db70e709ec6167704c9fab03d09b4a2bfb0bab2/ghds/ghds.go#L80

There should probably be an option for including them.
